# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149bae04afb1b66db7ed8a8d3f0f8033a907e0c3159250acb7f2f965206567ae574294f8c3df73c24bdca250ba149014bce5eb238443cf6da38d0321f79cfdeb

test:
  secret_key_base: cab65e584ad95b32b4ef9d38c09d3b8d70d3df1c298f424b578ef5ced8d5cd9def6a7a5716844941fdcc2b0b88fc1470886707f10c7530ca809e56c5c5fb2085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
